version: '3.8'

services:
  app:
    build:
      context: ./php
      dockerfile: Dockerfile
    deploy:
      replicas: 3
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./project/service:/var/www/html
    depends_on:
      - mysql
      - kafka
    networks:
      - app-network

#  consumer:
#    build:
#      context: ./consumer
#      dockerfile: Dockerfile
#    container_name: consumer
#    extra_hosts:
#      - "host.docker.internal:host-gateway"
#    restart: always
#    environment:
#      - KAFKA_GROUP_ID=consumer-group-1
#    volumes:
#      - ./project/src:/var/www/html
#    depends_on:
#      - app
#      - kafka
#    networks:
#      - app-network

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: nginx
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/logs:/var/log/nginx
    ports:
      - "${HTTP_PORT}:80"
    depends_on:
      - app
    networks:
      - app-network

  mysql:
    build:
      context: ./mysql
      dockerfile: Dockerfile
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: service
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "${DB_PORT}:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - app-network

  kafka:
    build:
      context: ./kafka
      dockerfile: Dockerfile
    container_name: kafka
    ports:
      - "${KAFKA_PORT}:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper
    networks:
      - app-network

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: "${ZOOKEEPER_CLIENT_PORT}"
      ZOOKEEPER_TICK_TIME: "${ZOOKEEPER_TICK_TIME}"
    ports:
      - "${ZOOKEEPER_PORT}:2181"
    networks:
      - app-network

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    ports:
      - "8080:8080"
    environment:
      - KAFKA_CLUSTERS_0_NAME=local
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:9092
      - KAFKA_CLUSTERS_0_ZOOKEEPER=zookeeper:2181
    depends_on:
      - app
      - kafka
    networks:
      - app-network

volumes:
  mysql-data:

networks:
  app-network:
    driver: bridge
