version: '3.8'

services:
  consumer-activity:
    build:
      context: ./consumer
      dockerfile: php/consumer/Dockerfile
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: always
    entrypoint: ["php", "cli", "event:consume", "--queue=activity"]
    volumes:
      - ./project/service:/var/www/html
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
